name = "MyProject"
uuid = "9c1f0d31-3776-4250-ada9-e246cbd360e2"
authors = ["Chengjun <tsunderepohwaran@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
